### ISSUE TITLE
control precision of display of energy

### ISSUE THREAD

**Issue by drew-parsons** [giacomomarchioro/PyEnergyDiagrams#10]
Nice tool.

At the moment the energy is written with the full precisions of the number provided to `add_level()`.
Would be nice if there was a simple control of the displayed precision. Perhaps at two levels, one in add_level(), and another for the ED() object, used if no precision control is given to add_level().

The use case would be taking energies directly from quantum chemical computational output, where they are reported to machine precision (16 or 20 digits), or at least reported to greater precision than you'd want to display in the energy diagram.

It can be done by feeding the value given the `add_level` through `round` e.g. `add_level( round(energy,3) )`, but the code could look tidier if the desired precision could be included in the ED API, e.g  `add_level( energy, precision=3 )`

**Comment by giacomomarchioro** [comment]
Hi, it seems a good idea, I'll implement it as soon as I have some free time.

Thanks for your feedback!
Giacomo

**Comment by giacomomarchioro** [comment]
Hi, 
commit  https://github.com/giacomomarchioro/PyEnergyDiagrams/commit/ccac18ffe1d0e0854e4503d9cd101c32877e7e42 allows you to control the number of digit globally:
```
a = ED()
a.round_energies_at_digit = 2
```
For changing the output of a single level, it is better to use this approach:
```
long_number = -19.81234123
a.add_level(long_number,'mCARB2','last',top_text=round(long_number,4))
```
This retains the full precision in the positioning of the level and change only the displayed value.

Making a particular method for handling this exception would add too much complexity to the code that I would like to keep very simple and minimal.

```
from energydiagram import ED
a = ED()
a.round_energies_at_digit = 2
a.add_level(0,'Separated Reactants')
a.add_level(-5.4234134,'mlC1')
a.add_level(-15.612341234,'mlC2','last',linestyle='dashed')
a.add_level(28.512341234,'mTS1',color='g')
a.add_level(-9.7123412342,'mCARB1')
long_number = -19.81234123
a.add_level(long_number,'mCARB2','last',top_text=round(long_number,4))
a.add_level(20,'mCARBX','last')
a.add_link(0,1,color='r')
a.add_link(0,2)
a.add_link(2,3,color='b')
a.add_link(1,3)
a.add_link(3,4,color='g')
a.add_link(3,5)
a.add_link(0,6)
a.add_electronbox(level_id=0, boxes=1, electrons=2, side=3, spacing_f=3)
a.add_electronbox(3,3,1,3,3)
a.add_electronbox(5,3,5,3,3)
a.add_arrow(6,4)
a.offset *= 2
a.plot(show_IDs=True)
```

I hope that this suit your needs. 

Best regards, 
Giacomo

**Comment by drew-parsons** [comment]
That makes sense.  We don't want to lose precision in the position of the level, I only want to control it in the display. The top_text approach works for me.

**Comment by giacomomarchioro** [comment]
Perfect, I am glad it helps.

`a.round_energies_at_digit = 2
`
Will also only affect the precision of the displayed text not that one of the positioning.

**Comment by drew-parsons** [comment]
Got it. It's a good solution.
