### ISSUE TITLE
allow different line styles for energy levels

### ISSUE THREAD

**Issue by drew-parsons** [giacomomarchioro/PyEnergyDiagrams#11]
At the moment energy levels (`add_level`) can be distinguished by color.  It could be nice to complement that with an `ls` option for different styles.

My use-case is that I want to compare the energy levels of the reactions of different isomers.  I want to use color to highlight the transition state, and distinguish the levels of different isomers (at the same x position) by linestyle, solid for one, dashed for the other.

Comparing with how color is used at https://github.com/giacomomarchioro/PyEnergyDiagrams/blob/406e82ea7576c9b8586218e56a91962034696427/energydiagram/energydiagram.py#L247
it would be easy enough to add an `ls` value alongside color. Something like `level[5]` in the `level` data object.

**Comment by giacomomarchioro** [comment]
Hi Drew, 
commit [11d05bf94faedba09acf84cdebf857c64d5c29a5](https://github.com/giacomomarchioro/PyEnergyDiagrams/commit/11d05bf94faedba09acf84cdebf857c64d5c29a5) should solve this isue now you can select the line style using the argument linestyle:

`a.add_level(-15.6,'mlC2','last',linestyle='dashed')
`

Let me know if it works.

All the best, 
Giacomo

**Comment by drew-parsons** [comment]
works fine, thanks!
