### ISSUE TITLE
Export to pgf,pdf and svg

### ISSUE THREAD

**Issue by skchemist** [giacomomarchioro/PyEnergyDiagrams#15]
Hi,
 how do I exactly save the plot as a pgf, pdf or svg file? 

Best, S

**Comment by giacomomarchioro** [comment]
Hi, 
at the end instad of using plt.show() you can use plt.savefig("myfig.pdf")

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html

**Comment by skchemist** [comment]
Thank you! But when I'm using plt.savefig("myfig.pdf") the pdf file is empty and I'm getting the response "<Figure size 432x288 with 0 Axes>". Do you have an idea where the problem is?

**Comment by giacomomarchioro** [comment]
Can you share the code?

**Comment by mit-eremin** [comment]
@giacomomarchioro, I used to do it as
```
diagram.fig.savefig(("test.pdf"), dpi=300, bbox_inches='tight')
```
But it now also does not work saying that ```AttributeError: 'NoneType' object has no attribute 'savefig'```

**Comment by giacomomarchioro** [comment]
> @giacomomarchioro, I used to do it as
> 
> ```
> diagram.fig.savefig(("test.pdf"), dpi=300, bbox_inches='tight')
> ```
> 
> But it now also does not work saying that `AttributeError: 'NoneType' object has no attribute 'savefig'`

This should be fixed now with https://github.com/giacomomarchioro/PyEnergyDiagrams/commit/8b89703ef504f98cdf2b566da60176351aa388ad

I don't understand, why are you enclosing "test.pdf" within brackets? Thanks for your feedback.

**Comment by mit-eremin** [comment]
thank you, @giacomomarchioro! The commit fixed it. Also, I left () by accident here, I usually use ```path.join``` there so erased it, but not the ().
