### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'set_ylabel'

### ISSUE THREAD

**Issue by mit-eremin** [giacomomarchioro/PyEnergyDiagrams#17]
I have recently updated the whole system and reinstalled all python packages, but seems like something went wrong with parts of PyEnergyDiagrams. When I run just the example
```
import matplotlib.pyplot as plt
from energydiagram import ED
%matplotlib inline
diagram = ED()
diagram.add_level(0,'Separated Reactants')
diagram.add_level(-5.4,'mlC1')
diagram.add_level(-15.6,'mlC2','last',) #Using 'last'  or 'l' it will be together with the previous level
diagram.add_level(28.5,'mTS1',color='g')
diagram.add_level(-9.7,'mCARB1')
diagram.add_level(-19.8,'mCARB2','l')
diagram.add_level(20,'mCARBX','last')
```
It plots the diagram, but when try to correct anything like ```diagram.ax.set_ylabel('My label')```, it gives me this:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 diagram.ax.set_ylabel('My label')

AttributeError: 'NoneType' object has no attribute 'set_ylabel'
```

```print(dir(diagram.ax))``` indeed does not show much

```
['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__',
'__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__',
'__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__',
'__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```

Hope there is an easy fix. Thank you!

**Comment by giacomomarchioro** [comment]
Hi, 
thanks for reporting it I found the commit that broke this feature. 
[76fa3064512c58761e31129e2daa6e42550051ba](https://github.com/giacomomarchioro/PyEnergyDiagrams/commit/0e4e953561e8673434169f436e3e81aec300c4b5)

I will try to fix it as soon as possible.

**Comment by giacomomarchioro** [comment]
https://github.com/giacomomarchioro/PyEnergyDiagrams/commit/8b89703ef504f98cdf2b566da60176351aa388ad
should fix this, can you please try to update the package and see if it works? 
Thanks!

**Comment by mit-eremin** [comment]
Thank you, @giacomomarchioro! Have updated it and seems like it works fine now
