### ISSUE TITLE
a.plot error when running examples

### ISSUE THREAD

**Issue by tanoury1** [giacomomarchioro/PyEnergyDiagrams#18]
Hi, I have been getting some unexpected results when running the tests, and the example shown in "How to use it?".

For "How to use it?":
1.  The plots are shown without using plt.show().  In fact, plt.show() does nothing, and plt.figsave("My.pdf") gives a blank page.
2.   When I try the fine tuning script I get the following error:

  C:\Users\tanoury\AppData\Local\Temp\ipykernel_28616\1857108825.py:11: UserWarning: Matplotlib is currently using module://matplotlib_inline.backend_inline, which is a non-GUI backend, so cannot show the figure.
  diagram.fig.show()

For the test scripts:
1. SimpleExample and ModifyPlot both throw an error at a.plot(show_IDs=True)   [although I did not get this error for the Electron Boxes example, nor any other example].  The error is:

TypeError                                 Traceback (most recent call last)
Input In [4], in <cell line: 21>()
     19 a.add_arrow(6, 4)
     20 a.offset *= 2
---> 21 a.plot(show_IDs=True)
     22 a.ax.set_ylabel('My label')
     23 a.fig.set_figwidth(10)

File ~\Miniconda3\lib\site-packages\energydiagram\energydiagram.py:308, in ED.plot(self, show_IDs, ylabel, ax)
    305         middle = y1-0.5*gap  # warning: this way works for negative HOMO/LUMO energies
    306         self.ax.annotate("", xy=(x1, y1), xytext=(x2, middle), arrowprops=dict(
    307             color='green', width=2.5, headwidth=5))
--> 308         self.ax.annotate(s=gapnew, xy=(x2, y2), xytext=(x1, middle), color='green', arrowprops=dict(width=2.5, headwidth=5, color='green'),
    309                     bbox=dict(boxstyle='round', fc='white'),
    310                     ha='center', va='center')
    312 for idx, link in enumerate(self.links):
    313     # here we connect the levels with the links
    314     # x1, x2   y1, y2
    315     for i in link:
    316         # i is a tuple: (end_level_id,ls,linewidth,color)

TypeError: annotate() missing 1 required positional argument: 'text'

Thank you and best regards,
Jerry

**Comment by giacomomarchioro** [comment]
Hi thanks for pointing it out. Regarding the second issue the problem is that newer version of matplotlib uses `text`instead of `s`changing it should fix it. 

I am trying to figure out why you encounter the first issue.  I let you know as soon as possible.

**Comment by giacomomarchioro** [comment]
Hi Jerry, 
if you install the module again with the newer version that I just released,  the issue regarding annotate should be solved. 

Regarding your first issue, I think that is related to your Python installation you could try to see this question: 
https://stackoverflow.com/questions/56656777/userwarning-matplotlib-is-currently-using-agg-which-is-a-non-gui-backend-so

Or try to run your example in an ipython qt-console and try to use a different backend using this command: `%matplotlib gtk

In my virtual environment it works as expected.

Thanks for reporting this issues!
All the best, 
Giacomo

**Comment by tanoury1** [comment]
Hi Giacomo,
I updated my Python install, and it helped a bit.  Here's what I am experiencing with the "How to use it?" example
1. If I:
import matplotlib.pyplot as plt
from energydiagram import ED

then, diagram.plot() will show the plot inline; plt.show() does nothing; diagram.fig.show() gives the error I showed before.

2. If I:
import matplotlib.pyplot as plt
from PyQt5.QtCore import QCoreApplication
matplotlib.use('QT5Agg')
from energydiagram import ED

then, diagram.plot() launches a new window which hangs in a perpetual cycle;
plt.show() does the same;
But, plt.savefig('Myfig.pdf') saves the expected figure.

So, all in all, using qt5 (or another GUI backend) turns off all inline plotting, and opens a separate GUI window being launched which gets caught in a loop.

Jerry

**Comment by giacomomarchioro** [comment]
mmm that's strange, I could not replicate this behaviour I suspect is something related with some GUI incompatibilities... 
I have create a colab notebook  and it seems it works fine, maybe you could you something similar:
https://colab.research.google.com/drive/18N1WW8RdFYnMpUOFM8MbnrDhgDipxA_U?usp=sharing

**Comment by tanoury1** [comment]
You are correct about the incompatibility issue. I set up a separate conda
environment using
Python 3.7 with Qt5 as the backend GUI.  It kinda worked. Which backend
GUI are you using?

Jerry

**Comment by giacomomarchioro** [comment]
I use module://ipykernel.pylab.backend_inline  and also MacOSX backend and they work I should test it on windows.
