### ISSUE TITLE
font size of labels

### ISSUE THREAD

**Issue by mberrens** [giacomomarchioro/PyEnergyDiagrams#20]
Hi, is there a way to change the font size of the energy levels?

**Comment by giacomomarchioro** [comment]
Hi, I will make a new release with this feature in a couple of days.

**Comment by giacomomarchioro** [comment]
Hi, now you can change the font size using: 

 ```
 a = ED()
 a.bottom_text_fontsize='xx-small'
 a.top_text_fontsize='xx-small'
```

Parameters description [here](https://matplotlib.org/stable/api/text_api.html#matplotlib.text.Text.set_fontsize)
