### ISSUE TITLE
Adding legend to the plot

### ISSUE THREAD

**Issue by harryws9** [giacomomarchioro/PyEnergyDiagrams#22]
Hi, loving the add-on - extremely useful!

I'm struggling to figure out how to add a legend to the plot. 
I have the energy levels of two different atoms in the same diagram (different colours), and I was wondering how to add a legend that says, for example, 
blue = atom1 
green = atom2

Many thanks,
Harry

**Comment by giacomomarchioro** [comment]
Hi you can use matplotlib if your `ED()` instance is called `diagram` you can use different colours for your compounds and then

```
from matplotlib.lines import Line2D
custom_lines = [Line2D([0], [0], color='g', lw=4),
                Line2D([0], [0], color='b', lw=4),
                Line2D([0], [0], color='y', lw=4),
                Line2D([0], [0], color='m', lw=4)]

```

```
diagram.ax.legend(custom_lines,
                 ['Green compound', 'Blue compound', 'Yellow compound','Magenta compound'],
                 bbox_to_anchor=(0.7,0.5),
                loc='upper left', borderaxespad=0.)
```

**Comment by harryws9** [comment]
Worked perfectly! Many thanks!
