### ISSUE TITLE
Trying to change size of diagram

### ISSUE THREAD

**Issue by masonhargrave** [giacomomarchioro/PyEnergyDiagrams#3]
Hi there! I am trying to change the size of the diagram made but I haven't figured out how. Does anyone know how to increase the width of the figure dynamically as well as the height?

Best,
Mason

**Comment by giacomomarchioro** [comment]
Hi,
Have you tried to enlarge the plot window directly?

Best regards,
Giacomi

Il mer 11 apr 2018, 22:40 masonhargrave <notifications@github.com> ha
scritto:

**Comment by masonhargrave** [comment]
The issue is not not much the size of the image but rather the fact that all of my labels are getting compressed:

```


from energydiagram import ED

diagram = ED()
diagram.add_level(0 + 0 + 1,'$n_x = 0 \n n_y = 0$')
diagram.add_level(1 + 0 + 1,'$n_x = 1 \n n_y = 0$')
diagram.add_level(0 + 1 + 1,'$n_x = 0 \n n_y = 1$')
diagram.add_level(2 + 0 + 1,'$n_x = 2 \n n_y = 0$')
diagram.add_level(1 + 1 + 1,'$n_x = 1 \n n_y = 1$')
diagram.add_level(0 + 2 + 1,'$n_x = 0 \n n_y = 2$')
diagram.add_level(3 + 0 + 1,'$n_x = 3 \n n_y = 0$')
diagram.add_level(2 + 1 + 1,'$n_x = 2 \n n_y = 1$')
diagram.add_level(1 + 2 + 1,'$n_x = 1 \n n_y = 2$')
diagram.add_level(0 + 3 + 1,'$n_x = 0 \n n_y = 3$'
```

This yields the following figure:

![image](https://user-images.githubusercontent.com/32820072/38643097-e675e772-3d90-11e8-8e9a-7e09a6ffa36d.png)


I managed to change the y easily enough, but the sizing is causing me issue.

**Comment by giacomomarchioro** [comment]
Hi,

yes I blocked the aspect ratio to add the electrons box features, seems
that the change didn't affect the results when I used energy differences
greater than 10 with 1or 2 and many level the ratio is wrong. I will fix
this bug as soon as possible but I think I will need  a week.

Try this work around in the meanwhile:

diagram = ED()
diagram.add_level(0 + 0 + 1,'$n_x = 0 \n n_y = 0$')
diagram.add_level(1 + 0 + 1,'$n_x = 1 \n n_y = 0$')
diagram.add_level(0 + 1 + 1,'$n_x = 0 \n n_y = 1$')
diagram.add_level(2 + 0 + 1,'$n_x = 2 \n n_y = 0$')
diagram.add_level(1 + 1 + 1,'$n_x = 1 \n n_y = 1$')
diagram.add_level(0 + 2 + 1,'$n_x = 0 \n n_y = 2$')
diagram.add_level(3 + 0 + 1,'$n_x = 3 \n n_y = 0$')
diagram.add_level(2 + 1 + 1,'$n_x = 2 \n n_y = 1$')
diagram.add_level(1 + 2 + 1,'$n_x = 1 \n n_y = 2$')
diagram.add_level(0 + 3 + 1,'$n_x = 0 \n n_y = 3$')
diagram.offset = 0.1
diagram.plot()
diagram.ax.axes.set_aspect('auto')
diagram.fig.show()


In case some forks should have the old version that it worked.

Best regards and thanks for spotting it,
Giacomo



2018-04-11 23:02 GMT+02:00 masonhargrave <notifications@github.com>:

**Comment by giacomomarchioro** [comment]
Dear masonhargrave,
I have improved the formatting now the results should be better, I also change a little bit your code there were some errors see below:

```
from energydiagram import ED

diagram = ED()
diagram.add_level(0 + 0 + 1,'$n_x = 0$ \n $n_y = 0$')
diagram.add_level(1 + 0 + 1,'$n_x = 1$ \n $n_y = 0$')
diagram.add_level(0 + 1 + 1,'$n_x = 0$ \n $n_y = 1$')
diagram.add_level(2 + 0 + 1,'$n_x = 2$ \n $n_y = 0$')
diagram.add_level(1 + 1 + 1,'$n_x = 1$ \n $n_y = 1$')
diagram.add_level(0 + 2 + 1,'$n_x = 0$ \n $n_y = 2$')
diagram.add_level(3 + 0 + 1,'$n_x = 3$ \n $n_y = 0$')
diagram.add_level(2 + 1 + 1,'$n_x = 2$ \n $n_y = 1$')
diagram.add_level(1 + 2 + 1,'$n_x = 1$ \n $n_y = 2$')
diagram.add_level(0 + 3 + 1,'$n_x = 0$ \n $n_y = 3$')

diagram.plot()
```
