### ISSUE TITLE
Python 2 ?

### ISSUE THREAD

**Issue by augtetenoire** [giacomomarchioro/PyEnergyDiagrams#5]
Good morning,

I was willing to use your program, however I doesn't seems to work because I'm using python3. As I don't use python2 I am not able to see if the program is wrote in python2 or not... But it seems to be the cause of why I can't use it...
Is that it ? If yes, do you have python3 version ?

Also, do you have possibility to make it as a pip package ?

Best regards.

**Comment by giacomomarchioro** [comment]
Hi, 
it should be compatible, what are the errors you are experiencing?

**Comment by augtetenoire** [comment]
Ok, I found the error... It was because I was subscripting badly in the string... My bad. 
Sorry for bothering you...

Thank you for your nice script !

**Comment by giacomomarchioro** [comment]
You are welcome I'll add the pip install in the next days, if you need any help let me know.

Best regards, 
Giacomo
