### ISSUE TITLE
TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by HenriqueCSJ** [giacomomarchioro/PyEnergyDiagrams#6]
Using a conda environment with python 3.7, matplotlib 3.1.3 and jupyter-notebook I'm getting this error:
TypeError                                 Traceback (most recent call last)
<ipython-input-11-315c1ac33a22> in <module>
----> 1 diagram.plot()

~/.local/lib/python3.7/site-packages/energydiagram/energydiagram.py in plot(self, show_IDs, ylabel)
    215 
    216         for level in data:
--> 217             start = level[1]*(self.dimension+self.space)
    218             ax.hlines(level[0], start, start + self.dimension, color=level[4])
    219             ax.text(start+self.dimension/2.,  # X

TypeError: can't multiply sequence by non-int of type 'float'

My input is exactly the same as your default example.

**Comment by giacomomarchioro** [comment]
Hi thanks for repoting this issue. At the moment just change `diagram.add_level(-19.8,'mCARB2','l')`
to `diagram.add_level(-19.8,'mCARB2','last').

I'll will update the code in the next hour so it can be used also the abbreviation 'l' for last.

Best regards, 
Giacomo

**Comment by giacomomarchioro** [comment]
Version "0.1.5" now support the abbreviation 'l' instead of using 'last'.  Thanks a lot for your feedback. Let me know if you encounter any other problem.
