### ISSUE TITLE
add_electronbox does not fill completely if box_number is greater than one.

### ISSUE THREAD

**Issue by agrass15268** [giacomomarchioro/PyEnergyDiagrams#7]
A command like
`diagram.add_electronbox(10,2,4)`

will produce an electron box containing only 3 electrons.
![error](https://user-images.githubusercontent.com/79014444/107854125-2aba7580-6e1a-11eb-99fa-7920529308b7.png)

The cause seems to be that in order to fill down-spin electrons `box_notation.py` iterates over `electrons_number%boxes_number`,
which in this case would give zero. A hard fix for single-box diagrams (setting it to 1) seems to be in place, however this does not work for more than one box.

I am actually somewhat unsure as to why the modulo is necessary in the first place - as an easy fix I simply replaced the iteration
`        else:
            for e in range(moduloelectrons):
                ax.add_patch(add_spin(Xi+box_side*e,Yi,box_side,direction='down'))`
with
`        else:
            for e in range(electrons_number-boxes_number):
                ax.add_patch(add_spin(Xi+box_side*e,Yi,box_side,direction='down'))`

This works perfectly, at least for 1-4 boxes and 1-8 electrons - I haven't tested it further.
As range() does not fire for values <=0 and only integers are accepted as arguments there should be no problems with that solution. It does, however, overfill the boxes if there are more electrons than fit in the box.

**Comment by giacomomarchioro** [comment]
Hi, thanks your are right. I never released this feature officially, I can't remember why I used the module it should be fixed now if you reinstall the newer version.

**Comment by agrass15268** [comment]
Yup, that works perfectly in all my test cases.

I just want to say that this is actually an incredibly useful feature, since creating spinplots is usually an incredibly annoying and fiddly task, so you might want to consider documenting it - I only stumbled upon it by accident.

Thank you for fixing it this quickly. Have a nice weekend.

**Comment by giacomomarchioro** [comment]
Yes your right I'll do it tomorrow. Have a nice weekend too.

All the best,
Giacomo

Il sab 13 feb 2021, 20:16 agrass15268 <notifications@github.com> ha scritto:
