### ISSUE TITLE
Hiding the axis values

### ISSUE THREAD

**Issue by akhilsnair2017** [giacomomarchioro/PyEnergyDiagrams#8]
Hi,
Many thanks for providing a script for plotting FEDs. I have been trying to hide the y axis values (-15.6,-5.4,etc.. in the example shown in github page) but did not work as it seems to be different from default matplotlib options. Could you please suggest a way to do this?

**Comment by giacomomarchioro** [comment]
Hi! Strange, what did you try?can you post your code? Are you sure you are not using the plot function again instead of using the handler after.?Eg. Diagram. Plot() diagram.ax.setticks etc. Etc. Plt.show()

**Comment by akhilsnair2017** [comment]
Here is my code ..

`import matplotlib.pyplot as plt
from energydiagram import ED
diagram = ED()
diagram.add_level(4.92,'$O_2$')
diagram.add_level(3.11,'OOH')
diagram.add_level(2.02,'O')
diagram.add_level(1.78,'OH')
diagram.add_level(0,'$H_2O$')
diagram.add_link(0,1)
diagram.add_link(1,2)
diagram.add_link(2,3)
diagram.add_link(3,4)
diagram.plot(ylabel="Energy (eV)")#,xlabel="reaction coordinate")
`plt.show()``

I would like to hide the y axis values like 4.92,3.11,etc.. here keeping the labels O2,O, OH, ..as it is.  Also when i added an xlabel by name 'reaction coordinate' it is not being taken. 

Thanks

**Comment by akhilsnair2017** [comment]
Thanks for replying, here is the code i tried;
import matplotlib.pyplot as plt
from energydiagram import ED
diagram = ED()
diagram.add_level(4.92,'$O_2$')
diagram.add_level(3.11,'OOH')
diagram.add_level(2.02,'O')
diagram.add_level(1.78,'OH')
diagram.add_level(0,'$H_2O$')
diagram.add_link(0,1)
diagram.add_link(1,2)
diagram.add_link(2,3)
diagram.add_link(3,4)
diagram.plot(ylabel="Energy (eV)")#,xlabel="reaction coordinate")
diagram.plot(yticks='')
plt.show()

I would like to hide the yaxis values such as 4.92,3.11 keeping the labels O2, O etc as it is. Also when i tried to add xlabel in diagram.plot(), its not being taken

**Comment by akhilsnair2017** [comment]
Hi,
I had solved it by inspecting the code and by giving an empty string to the top_text argument in diagram.add_level(). Thanks for replying. I would like to limit my query to adding xaxis label alone. Also since i required the first level to start exactly from the yaxis, i have tried by varying the negative values in  'position' argument inside diagram.add_level(). But it does not seem to shift the level. Could you please suggest a way to solve this?

**Comment by giacomomarchioro** [comment]
Hi, 
basically you can access all the  matplotlib parameters using `diagram.ax.` and `diagram.fig.` 


```
import matplotlib.pyplot as plt
from energydiagram import ED
diagram = ED()
diagram.add_level(4.92,'$O_2$')
diagram.add_level(3.11,'OOH')
diagram.add_level(2.02,'O')
diagram.add_level(1.78,'OH')
diagram.add_level(0,'$H_2O$')
diagram.add_link(0,1)
diagram.add_link(1,2)
diagram.add_link(2,3)
diagram.add_link(3,4)
diagram.plot(ylabel="Energy (eV)")
# Hiding the yticks
diagram.ax.set_yticks([])
# showing the x axis ticks
diagram.ax.axes.get_xaxis().set_visible(True)
#showing x axis frame
diagram.ax.spines['bottom'].set_visible(True)
# change the x axis label
diagram.ax.set_xlabel("MYlable")
plt.show()
```
